### ISSUE TITLE
Feature request: Add close menu from task bar

### ISSUE THREAD

**Issue by Jolg42** [socketsupply/beta#11]
<img width="31" alt="Screen Shot 2021-01-11 at 18 11 57" src="https://user-images.githubusercontent.com/1328733/104215084-93d45500-5438-11eb-9dad-bed40433bdec.png">
The icon in the task bar makes the app visible but there is no easy way to kill the app.

I used the Activity Monitor right now.

Having a close app from the task bar icon would be great.

**Comment by heapwolf** [comment]
![image](https://user-images.githubusercontent.com/136109/104216226-0f82d180-543a-11eb-876c-e094a218c282.png)

There is a way to close it so you don't have to kill it with fire, click `Shutdown all operator apps`. but I agree.

**Comment by Jolg42** [comment]
Indeed that works but it's extra clicks around to find it.

**Comment by Raynos** [comment]
We've implemented a close icon, our apps are now windows that can be closed. 

We released new binaries this week ( https://socketsupply.co/download )
