### ISSUE TITLE
Operator: Feedback form takes a long time

### ISSUE THREAD

**Issue by juliangruber** [socketsupply/beta#26]
![image](https://user-images.githubusercontent.com/10247/105819316-50412580-5fb8-11eb-9c13-8f2e388aa2f3.png)

It just looks to be stuck here

**Comment by juliangruber** [comment]
Here is the error I was trying to submit:



### STACK

```
Error: Uncaught Error: Error invoking remote method 'api': Error: IPC api feedback:postFeedback has uncaught: arg.license required
```


### SYSTEM SUMMARY

```
Operator v0.1.18
Windows_NT x64 10.0.19041

Wizards: v0.1.18
Buckets: v0.1.10
Functions: v0.1.13
Data: v0.1.7
Electron: v11.1.1
```

I was trying to update `Functions`, which did also launch after all.

**Comment by Raynos** [comment]
hmm, this is issue is fixed in wizards `0.1.30` ;

I think once your updated to latest the problem will go away.

**Comment by juliangruber** [comment]
is wizards the operator app?

**Comment by Raynos** [comment]
That's a good question, yes `wizards` is the operator application.

**Comment by Raynos** [comment]
Renaming Wizards => Operator and Operator => Operator Binary could make it clearer what is what in terms of versions.
