### ISSUE TITLE
add credentials on free edition

### ISSUE THREAD

**Issue by dominictarr** [socketsupply/beta#29]
It can't find my amazon credentials. I created an access key, downloaded it (I thought I would give it the file or something) but it seems to expect it to be somewhere particular but the guide it linked to doesn't say anything about that.

I'm guessing there is a aws cli tool that has a convention about this but the guide on how to create credentials doesn't explain what to use

**Comment by dominictarr** [comment]
aws gives me an option to download a key file. so I have a rootkey.csv in my downloads folder

**Comment by Raynos** [comment]
There's two ways of bootstrapping AWS creds.

 - Use the aws cli with `aws configure` ( https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html ).
 - Create an AWS access key for an IAM user in the AWS console ( https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey ) and then copy the access key & secret into the Operator setup.
 
We have an outdated docs page ( https://optool.co/docs/?get-started/running-operator-toolbox ).

We should change our first time wizard experience and/or link out to an updated docs page to make this smoother.

**Comment by dominictarr** [comment]
to "copy the access key & secret into the operatior setup" where should it go?

**Comment by Raynos** [comment]
In the first time experience you can configure the profiles

![image](https://user-images.githubusercontent.com/479538/120768300-47d79900-c51c-11eb-894b-b50e00381d91.png)

OK never mind, I tried clicking `here` and there's a bug with it. It doesnt show the inputs to enter access & secret.

**Comment by Raynos** [comment]
I released a new version of the app for nightly

https://optool.co/download/?nightly

Do you want to try this version, it should allow you to add profiles when you have no profiles

**Comment by heapwolf** [comment]
Fixed in current prerelease.
